data:
  init:
    _target_: Data.Data_train
    path_train_ds: ${data.path.directory}/${data.path.train.name}/${data.path.train.nc}
    path_valid_ds: ${data.path.directory}/${data.path.valid.name}/${data.path.valid.nc}
  input:
    dir_seg_models: /cerea_raid/users/dumontj/dev/coco2/dl/res/models
    chan_0: xco2
    chan_1: no2
    chan_2: seg_2km_64_ber_no2
    chan_3: u_wind
    chan_4: v_wind
  output:
    N_emissions: 1
  path:
    directory: /Users/xiaoxubeii/Downloads/data_paper_inv_pp
    train:
      name: all_hotspots_but_lip
      nc: train_dataset.nc
    valid:
      name: ${data.path.train.name}
      nc: valid_dataset.nc
dir_res: res/${model.type}
exp_name: inv_lip_essential
seed: 42
sweep: false
model:
  type: inversion
  name: essential
  loss_func: MeanAbsoluteError
  dropout_rate: 0.2
  scaling_coefficient: 1
training:
  batch_size: 32
  learning_rate: 0.001
  max_epochs: 500
  init_weights: random
  optimiser: adam
augmentations:
  shuffle: true
  rot:
    range: 180
  shift:
    range: 0
  flip:
    bool: true
  shear:
    range: 90
  zoom:
    range: 0.2
  plume_scaling_max: 2
  plume_scaling_min: 0.25
callbacks:
  model_checkpoint:
    __target__: true
  learning_rate_monitor:
    __target__: true
    factor: 0.5
    patience: 20
    min_delta: 0.005
    min_lr: 5.0e-05
    cooldown: 0
  wandb:
    __target__: true
